spring:
  application:
    name: automarket

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}

# Общие настройки
springdoc:
  api-docs.path: /api/docs
  swagger-ui.path: /api/swagger

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
