spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  cors:
    origins: ${CORS_ORIGINS}

firebase:
  enabled: true
