spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/automarket
    username: automarket
    password: aibeni
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8080

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  cors:
    origins: http://localhost:5173,http://localhost:5208,http://localhost:5209
    
firebase:
  enabled: true

logging:
  level:
    org.springframework.security: INFO
